name: Linters
on:
  push:
    branches: [main]
jobs:
  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint with ESLint
        run: pnpm run eslint
  stylelint:
    runs-on: ubuntu-latest
    name: Stylelint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint with Stylelint
        run: pnpm run stylelint
