name: Linters
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint and Stylelint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint with ESLint
        run: pnpm run eslint && pnpm run stylelint
